apiVersion: apps/v1
kind: Deployment

metadata:
  name: healthcare-app
  namespace: healthcare

spec:
  replicas: 2

  selector:
    matchLabels:
      app: healthcare-app

  template:
    metadata:
      labels:
        app: healthcare-app

    spec:
      containers:
      - name: healthcare-app

        image: YOUR_DOCKERHUB_USERNAME/healthcare-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"

          limits:
            memory: "256Mi"
            cpu: "200m"

        readinessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 5000

          initialDelaySeconds: 15
          periodSeconds: 10